[package]
name = "payflow"
version = "1.0.0"
authors = ["PayFlow Team"]
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
payflow = "0x0"
std = "0x1"

[dev-addresses]
payflow = "0x0"
